/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_appsync_graphqlEndpoint": "https://kou5io4vzbh4tdvcz6saq7e3vu.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-w3omjwe6cnbddpf4b4zaozliyu",
    "aws_cognito_identity_pool_id": "us-west-2:60516a8e-1a3b-43af-9a04-e2c68ba554da",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_tlTVcd0Xf",
    "aws_user_pools_web_client_id": "26dl3tjp98mu3gqulkdvqsqteh",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
